### ISSUE TITLE
WebSocketの導入

### ISSUE THREAD

**Issue by tt-kuma** [kusumotolab/kGenProg-online-demo#1]
**現状**
ajaxによるpolling形式（200ms更新，地獄）．
これをrealtimeにやりたい．
front/back両方の修正が必要．

**実装の方針**
wsブランチから始めるべき
kgpのstdoutの更新がある度に，wsのデータ送信 & ファイル追記をする．

1. 現状のkdemoのフロントエンドにws周りの機能を追加する
（現状のpollingは残す，wsの結果はbrowser-consoleに吐き出す）
2. それが動くようにバックエンドを更新する
3. フロントエンドのpolling削除して，wsをkdemo-consoleに吐き出す

**おいおい決めること（仮決定）**
- wsのendpoint `ws://kdemo/{key}`
- wsのデータ構造 `{stdout: "xx\n"}`

**Comment by shinsuke-mat** [comment]
手順1，フロントエンドはdone
> 現状のkdemoのフロントエンドにws周りの機能を追加する
>（現状のpollingは残す，wsの結果はbrowser-consoleに吐き出す）

https://github.com/kusumotolab/kGenProg-online-demo/tree/ws

**Comment by shinsuke-mat** [comment]
[kuma]

バックエンドのwsを実装してpushしました．
変更点としては
- /api/submission/ にpostした時点でconfをディスクに展開 (kgpはまだ実行しない)
- wsのコネクションが確立された時点でkgpの実行開始

**Comment by shinsuke-mat** [comment]
上記変更をクライアントに取り込みました．
最低限，wsが動作するようになりました．

1点リクエスト．
/api/submission が終わったらサーバから明示的にwsのコネクションを切断してください．
`ws.close()` を適切なタイミングで呼ぶ問題です．

理由：
- 現状，単一クライアントが無限にwsコネクションを持ててしまう
![image](https://user-images.githubusercontent.com/5342911/80265113-6c363480-86d1-11ea-91ce-6944b1284aa3.png)

- UIの都合で `repair` ボタンを一時的にdisableしている．enableにするタイミングがクライアントからは判別できない

**Comment by tt-kuma** [comment]
kgp実行終了後サーバ側からwsのコネクションをcloseするよう変更しました．
![image](https://user-images.githubusercontent.com/49231795/80266412-b1a93080-86d6-11ea-8ebd-9bba189c3ae6.png)

**Comment by shinsuke-mat** [comment]
UIも正しく動いてるのでmasterマージします
