### ISSUE TITLE
Dockerfileのリファクタリング

### ISSUE THREAD

**Issue by tt-kuma** [kusumotolab/kGenProg-online-demo#2]
**現状**
機能的には全く問題ない．
とりあえず動くだけできれいじゃない．

**todo**
現状のdockerfileをgitに設置する．
`run.sh` → `build.sh`
`FROM` も考える
dockerのプラクティスに従って「良い」dockerfileにする．

**Comment by tt-kuma** [comment]
nodeプロジェクトの場合
```
COPY . .
RUN npm install
```
とするより
```
COPY package*.json ./
RUN npm install
COPY . .
```
のほうが良い．
前者はnodeプロジェクト中のソースコードに変更がある度に`npm install`が走る．
後者はソースコードに変更があっても`package*.json`に変更がなければキャッシュを活用できるため速い．
https://nodejs.org/ja/docs/guides/nodejs-docker-webapp/

**Comment by tt-kuma** [comment]
FROMを変えるだけでコンテナサイズがかなり変わる
- `kdemo-alpine`: `FROM node:12-alpine`
- `kdemo-buster`: `FROM node:12-buster` (busterはdebianのバージョン, `FROM node:12`とほぼ同じ)
- `kdemo-buster-slim`: `FROM node:12-buster-slim` (slimは最小限のパッケージのみデフォルトでインストール)
![image](https://user-images.githubusercontent.com/49231795/80853356-16323580-8c6b-11ea-8dee-72c87d479ea3.png)

**Comment by shinsuke-mat** [comment]
さらにリファクタリングを加えた．

特にkgpのver指定部分を`ARG`に差し替えた．
必要に応じて手でver指定を変更すれば良い．
自動更新は以下のケースもあるのでやらない方が吉．
https://github.com/kusumotolab/kGenProg/issues/773
