### ISSUE TITLE
kgpデフォルトパラメタの見直し

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg-online-demo#6]
demoである & セキュリティ的にまずい，
の2つの理由からkdemoの実行パラメタはシビアに設定している．
max1分, 10世代

当然，修正能力に強い制約が生まれてしまっている．

どうあるべきか？

**Comment by tt-kuma** [comment]
研究室見学用に一時的に以下の数値に変更
- 最大世代数1000
- 時間制限5分
